export const unidades = [
  {
    id: 1,
    cidade: 'Tubarão',
    uf: 'SC',
    endereco: 'R. Hermes Esmeraldino, 90 — São João Margem Esquerda',
    telefone: '(48) 3621-5050',
    matriz: true,
  },
  {
    id: 2,
    cidade: 'Criciúma',
    uf: 'SC',
    endereco: 'Av. Centenário, 2340 — Centro',
    telefone: '(48) 3437-2200',
    matriz: false,
  },
  {
    id: 3,
    cidade: 'Florianópolis',
    uf: 'SC',
    endereco: 'Av. Beira Mar Norte, 1500 — Centro',
    telefone: '(48) 3025-8800',
    matriz: false,
  },
  {
    id: 4,
    cidade: 'Lages',
    uf: 'SC',
    endereco: 'R. Coronel Córdova, 480 — Centro',
    telefone: '(49) 3222-4110',
    matriz: false,
  },
  {
    id: 5,
    cidade: 'Porto Alegre',
    uf: 'RS',
    endereco: 'Av. Ipiranga, 6681 — Partenon',
    telefone: '(51) 3232-7700',
    matriz: false,
  },
  {
    id: 6,
    cidade: 'Caxias do Sul',
    uf: 'RS',
    endereco: 'R. Sinimbu, 1890 — Centro',
    telefone: '(54) 3221-9040',
    matriz: false,
  },
]
